version: "3"

services:
  mongo:
    image: "mongo:7.0.6"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: maliciousIPs
      MONGO_INITDB_ROOT_USERNAME: korelor
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - /var/mongo/maliciousIPs:/data/db
    user: 1004:1004

  mongo-express:
    image: 'mongo-express:1.0.2-20-alpine3.19'
    restart: always
    deploy: 
      mode: replicated
      replicas: 1
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: korelor
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
      ME_CONFIG_MONGODB_URL: mongodb://korelor:mongo@mongo:27017/