services:
  ip-address:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      VT_API_KEY: ${VT_API_KEY}
      MG_USER_NAME: ${MG_USER_NAME}
      MG_PASSWORD: ${MG_PASSWORD}

  mongo:
    image: "mongo:7.0.6"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: maliciousIPs
      MONGO_INITDB_ROOT_USERNAME: ${MG_USER_NAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MG_PASSWORD}
    volumes:
      - /var/mongo/maliciousIPs:/data/db
    user: 1004:1004

  mongo-express:
    image: 'mongo-express:1.0.2-20-alpine3.19'
    restart: always
    deploy: 
      mode: replicated
      replicas: 1
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MG_USER_NAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MG_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MG_USER_NAME}:${MG_PASSWORD}@mongo:27017/